
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA IDENTIFIER LBRACKET NUMBER RBRACKET SEMICOLON TYPEdeclaration : type var_list SEMICOLONtype : TYPEvar_list : varvar_list : var COMMA var_listvar : IDENTIFIER\n           | IDENTIFIER LBRACKET NUMBER RBRACKET'
    
_lr_action_items = {'TYPE':([0,],[3,]),'$end':([1,7,],[0,-1,]),'IDENTIFIER':([2,3,8,],[6,-2,6,]),'SEMICOLON':([4,5,6,10,12,],[7,-3,-5,-4,-6,]),'COMMA':([5,6,12,],[8,-5,-6,]),'LBRACKET':([6,],[9,]),'NUMBER':([9,],[11,]),'RBRACKET':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'type':([0,],[2,]),'var_list':([2,8,],[4,10,]),'var':([2,8,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> type var_list SEMICOLON','declaration',3,'p_declaration','v1.py',29),
  ('type -> TYPE','type',1,'p_type','v1.py',33),
  ('var_list -> var','var_list',1,'p_var_list_single','v1.py',37),
  ('var_list -> var COMMA var_list','var_list',3,'p_var_list_multiple','v1.py',41),
  ('var -> IDENTIFIER','var',1,'p_var','v1.py',45),
  ('var -> IDENTIFIER LBRACKET NUMBER RBRACKET','var',4,'p_var','v1.py',46),
]
